cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    demouser:
      email: demouser@gmail.com
      failed_login_attempts: 0
      first_name: Demo
      last_name: User
      logged_in: false
      password: $2b$12$FZnYku7eNs2WhXG/dP3AQ.8S1xuF7irV4AFpt7.eGyEIBYIcmh4oO
